# Generated by Django 4.1.2 on 2022-11-24 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_product_books', '0008_rename_created_date_bookcard_date_entered_catalog'),
        ('app_reference_book', '0007_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Корзина пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='app_orders.cart', verbose_name='Заказ')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_reference_book.status', verbose_name='Статус заказа')),
            ],
        ),
        migrations.CreateModel(
            name='BookInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_product_books.bookcard', verbose_name='Book in cart')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_in_cart', to='app_orders.cart', verbose_name='Cart')),
            ],
        ),
    ]
