# Generated by Django 4.1.2 on 2022-11-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_alter_orderall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderall',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='app_orders.cart', verbose_name='Заказ'),
        ),
    ]
