# Generated by Django 4.1.2 on 2022-11-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_book', '0007_status'),
        ('app_orders', '0003_alter_orderall_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderall',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='orderall',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='orderall',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='orderall',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='orderall',
            name='status',
            field=models.ForeignKey(default='Ожидает обработки', on_delete=django.db.models.deletion.PROTECT, related_name='order', to='app_reference_book.status', verbose_name='Статус заказа'),
        ),
    ]
