# Generated by Django 4.1.2 on 2022-11-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0004_alter_orderall_address_alter_orderall_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderall',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='app_orders.cart', verbose_name='Корзина'),
        ),
    ]
