# Generated by Django 4.1.2 on 2022-12-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_book', '0008_alter_genres_description_alter_genres_name_and_more'),
        ('app_orders', '0005_alter_orderall_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderall',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='app_reference_book.status', verbose_name='Статус заказа'),
        ),
    ]
