# Generated by Django 4.1.2 on 2022-12-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0006_alter_orderall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
