# Generated by Django 4.1.2 on 2022-12-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_books', '0011_alter_bookcard_publishing'),
        ('app_orders', '0007_alter_bookincart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_to_book_in_cart', to='app_product_books.bookcard', verbose_name='Book in cart'),
        ),
    ]
