# Generated by Django 4.1.2 on 2022-10-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_book', '0003_genres_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/%Y/%m/%d', verbose_name='authors photo'),
        ),
    ]
