# Generated by Django 4.1.2 on 2022-11-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_book', '0004_authors_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='last_name',
        ),
        migrations.AddField(
            model_name='authors',
            name='first_last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/Authors/', verbose_name='authors photo'),
        ),
    ]
