# Generated by Django 4.1.2 on 2022-11-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_book', '0005_remove_authors_first_name_remove_authors_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='first_last_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/Authors/', verbose_name='Фотография'),
        ),
    ]
