# Generated by Django 4.1.2 on 2022-11-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_reference_book', '0004_authors_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='upload/books/%Y/%m/%d', verbose_name='Book picture')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('year_of_publishing', models.PositiveSmallIntegerField()),
                ('pages', models.PositiveSmallIntegerField()),
                ('cover', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField()),
                ('age_restrictions', models.CharField(max_length=4)),
                ('availability', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('date_entered_catalog', models.DateField(auto_now_add=True)),
                ('date_last_modified', models.DateField(auto_now=True)),
                ('authors', models.ManyToManyField(to='app_reference_book.authors')),
                ('genre', models.ManyToManyField(to='app_reference_book.genres')),
                ('publishing', models.ManyToManyField(to='app_reference_book.publishinghouse')),
                ('serie', models.ManyToManyField(to='app_reference_book.series')),
            ],
        ),
    ]
