# Generated by Django 4.1.2 on 2022-11-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_books', '0002_alter_bookcard_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcard',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
