# Generated by Django 4.1.2 on 2022-11-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_books', '0003_bookcard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='description',
            field=models.TextField(),
        ),
    ]
