# Generated by Django 4.1.2 on 2022-11-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_book', '0005_remove_authors_first_name_remove_authors_last_name_and_more'),
        ('app_product_books', '0004_alter_bookcard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='serie',
            field=models.ManyToManyField(blank=True, to='app_reference_book.series', verbose_name='Серия'),
        ),
    ]
