# Generated by Django 4.1.2 on 2022-11-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_books', '0005_alter_bookcard_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена (BYN)'),
        ),
    ]
