# Generated by Django 4.1.2 on 2022-11-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_books', '0006_alter_bookcard_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcard',
            old_name='date_entered_catalog',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='bookcard',
            old_name='date_last_modified',
            new_name='updated_date',
        ),
    ]
