# Generated by Django 4.1.2 on 2022-11-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_books', '0007_rename_date_entered_catalog_bookcard_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcard',
            old_name='created_date',
            new_name='date_entered_catalog',
        ),
    ]
