# Generated by Django 4.1.2 on 2022-11-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_book', '0008_alter_genres_description_alter_genres_name_and_more'),
        ('app_product_books', '0008_rename_created_date_bookcard_date_entered_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='authors',
            field=models.ManyToManyField(related_name='Book', to='app_reference_book.authors', verbose_name='Авторы книги'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='date_entered_catalog',
            field=models.DateField(auto_now_add=True, verbose_name='Дата внесения в каталог'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения карточки'),
        ),
    ]
