# Generated by Django 4.1.2 on 2022-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_book', '0008_alter_genres_description_alter_genres_name_and_more'),
        ('app_product_books', '0009_alter_bookcard_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='genre',
            field=models.ManyToManyField(related_name='Book', to='app_reference_book.genres', verbose_name='Жанр'),
        ),
    ]
