# Generated by Django 4.1.2 on 2022-12-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_books', '0013_alter_bookcomments_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcard',
            name='comments',
        ),
        migrations.AddField(
            model_name='bookcomments',
            name='bookcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookcomments', to='app_product_books.bookcard', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookcomments',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
