# Generated by Django 4.1.2 on 2022-12-05 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефон')),
                ('address_country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна')),
                ('address_city', models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна')),
                ('address_index', models.SmallIntegerField(verbose_name='Индекс')),
                ('address_fist', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 1')),
                ('address_second', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 2')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
