# Generated by Django 4.1.2 on 2022-12-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='address_city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Город'),
        ),
    ]
