# Generated by Django 4.1.2 on 2022-12-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_alter_userextension_address_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='address_index',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Индекс'),
        ),
    ]
