# Generated by Django 4.1.2 on 2022-12-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0004_alter_userextension_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextension',
            options={'permissions': (('access_for_customers', 'Customers can see it'),)},
        ),
    ]
